### ISSUE TITLE
EN PROD ET SUR FIREFOX

### ISSUE THREAD

**Issue by codelande** [WildCodeSchool/2022-03-php-orleans-project-aoyos#556]
Les cards côté visiteur sont toutes buggués (taille, emplacement, etc)
Lien pour télécharger/supprimer les images souvent présent et non stylisés

Je pense que j'ai mal initialisé le site en mode prod ou qie mozilla fait des siennes car aucun pb en dev

**Comment by Ysedda** [comment]
GG
